
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import models.drivers;
import javax.swing.DefaultComboBoxModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author EVELYN
 */
public class Driver_Details extends javax.swing.JFrame {

    Connection connection = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
   //populating a combobox with driver ids from the  driver table 
     public void setDriver(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/fleetdb", "root", "");
            ArrayList<String> groupNames = new ArrayList<String>();
            String sql = "Select Driver_id from driver";
            PreparedStatement ps = connection.prepareStatement(sql);
            rs = ps.executeQuery();
            while (rs.next()) {
                String name = rs.getString("Driver_id");
                System.out.println(name);
                groupNames.add(name);

            }
            rs.close();
            
            //        Populate ComboBox 

        DefaultComboBoxModel model = new DefaultComboBoxModel(groupNames.toArray());
        driver_idCombo.setModel(model);
             }
        catch(Exception e){
        e.printStackTrace();
                }
    
     }
    /**
     * Creates new form Driver_Details
     */
    public Driver_Details(){
        initComponents();
        show_driver();
        //combobox method
         setDriver();
    }
       
//populating jtable from driver database
    public ArrayList<drivers> driverlist() {
        ArrayList<drivers> driverlist = new ArrayList<>();
        try {

            Class.forName("com.mysql.jdbc.Driver");
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/fleetdb", "root", "");
            String sql = "Select * from driver";
            ps = connection.prepareStatement(sql);
            rs = ps.executeQuery();
            drivers driver;
            while (rs.next()) {
                driver = new drivers(rs.getInt("driver_id"),
                        rs.getString("First_name"),
                        rs.getString("Last_name"),
                        rs.getString("Gender"),
                        rs.getInt("Phone_number"));
                driverlist.add(driver);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return driverlist;

    }

    public void show_driver() {
        ArrayList<drivers> list = driverlist();
        DefaultTableModel model = (DefaultTableModel) jTable_Display_Driver.getModel();
        Object[] row = new Object[6];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getDriver_id();
            row[1] = list.get(i).getFirst_name();
            row[2] = list.get(i).getLast_name();
            row[3] = list.get(i).getGender();
            row[4] = list.get(i).getPhone_number();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Display_Driver = new javax.swing.JTable();
        adddriver = new javax.swing.JButton();
        deletedriver = new javax.swing.JButton();
        label1 = new java.awt.Label();
        firstname = new java.awt.TextField();
        label2 = new java.awt.Label();
        lastname = new java.awt.TextField();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        phonenumber = new java.awt.TextField();
        jLabel2 = new javax.swing.JLabel();
        updatedriver = new javax.swing.JButton();
        label5 = new java.awt.Label();
        driver_idCombo = new javax.swing.JComboBox<>();
        maleradiobtn = new javax.swing.JRadioButton();
        femaleradiobtn = new javax.swing.JRadioButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WELCOME TO LYNX FLEET MANAGEMENT SYSTEM");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        back.setBackground(new java.awt.Color(255, 255, 255));
        back.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        back.setForeground(new java.awt.Color(0, 0, 0));
        back.setText("BACK");
        back.setBorder(null);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jTable_Display_Driver.setBackground(new java.awt.Color(77, 184, 255));
        jTable_Display_Driver.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Driver id", "First name", "Last name", "Gender", "Phone number"
            }
        ));
        jTable_Display_Driver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_Display_DriverMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_Display_Driver);

        adddriver.setBackground(new java.awt.Color(255, 255, 255));
        adddriver.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        adddriver.setForeground(new java.awt.Color(0, 0, 0));
        adddriver.setText("ADD DRIVER");
        adddriver.setBorder(null);
        adddriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adddriverActionPerformed(evt);
            }
        });

        deletedriver.setBackground(new java.awt.Color(255, 255, 255));
        deletedriver.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        deletedriver.setForeground(new java.awt.Color(0, 0, 0));
        deletedriver.setText("DELETE DRIVER");
        deletedriver.setBorder(null);
        deletedriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletedriverActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("First Name");

        firstname.setBackground(new java.awt.Color(255, 255, 255));

        label2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("Last Name");

        lastname.setBackground(new java.awt.Color(255, 255, 255));
        lastname.setForeground(new java.awt.Color(255, 255, 255));

        label3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setText("Gender");

        label4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label4.setForeground(new java.awt.Color(255, 255, 255));
        label4.setText("Phone Number");

        phonenumber.setBackground(new java.awt.Color(255, 255, 255));
        phonenumber.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(" LYNX FLEET MANAGEMENT SYSTEM");

        updatedriver.setBackground(new java.awt.Color(255, 255, 255));
        updatedriver.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        updatedriver.setForeground(new java.awt.Color(0, 0, 0));
        updatedriver.setText("UPDATE DRIVER");
        updatedriver.setBorder(null);
        updatedriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatedriverActionPerformed(evt);
            }
        });

        label5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label5.setForeground(new java.awt.Color(255, 255, 255));
        label5.setText("DRIVER ID");

        driver_idCombo.setBackground(new java.awt.Color(255, 255, 255));
        driver_idCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                driver_idComboActionPerformed(evt);
            }
        });

        maleradiobtn.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(maleradiobtn);
        maleradiobtn.setForeground(new java.awt.Color(0, 0, 0));
        maleradiobtn.setText("MALE");
        maleradiobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleradiobtnActionPerformed(evt);
            }
        });

        femaleradiobtn.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(femaleradiobtn);
        femaleradiobtn.setForeground(new java.awt.Color(0, 0, 0));
        femaleradiobtn.setText("FEMALE");
        femaleradiobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleradiobtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1433, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(175, 175, 175)
                                .addComponent(deletedriver, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(138, 138, 138)
                                .addComponent(updatedriver, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(adddriver, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(label5, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(driver_idCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(maleradiobtn)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(femaleradiobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(phonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 932, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(828, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(driver_idCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(maleradiobtn)
                                .addComponent(femaleradiobtn)))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(updatedriver, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(adddriver, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(deletedriver, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(209, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:

        Admin_dashboard admin = new Admin_dashboard();
        admin.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_backActionPerformed

    private void updatedriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatedriverActionPerformed
        // TODO add your handling code here:

        //UPDATE_DRIVER updatedriver=new UPDATE_DRIVER();
        //updatedriver.setVisible(true);
        //this.setVisible(false);
        try{
       connection=DriverManager.getConnection("jdbc:mysql://localhost:3306/fleetdb","root","");
        ps = connection.prepareStatement("UPDATE driver SET `First_name`=?, `Last_name`=? ,`Gender`=? ,`Phone_number`=? WHERE `Driver_id`=?");
         ps.setString(1, firstname.getText());
         ps.setString(2, lastname.getText());
         ps.setString(3, gender);
          ps.setString(4, phonenumber.getText());
           String value = driver_idCombo.getSelectedItem().toString();
                   ps.setString(5,value);
           int rowaffected=ps.executeUpdate();
                if( rowaffected>0 ){
            System.out.println("updated");
            JOptionPane.showMessageDialog(null,"DRIVER UPDATED SUCCESSFULLY");
        }
                  System.out.println("updated");
            JOptionPane.showMessageDialog(null,"VEHICLE UPDATED SUCCESSFULLY");
        }
       
        catch(Exception e){
            e.printStackTrace();
        
        }
    }//GEN-LAST:event_updatedriverActionPerformed

    private void adddriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adddriverActionPerformed
        // TODO add your handling code here:
        ADD_DRIVER adddriver = new ADD_DRIVER();
        adddriver.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_adddriverActionPerformed

    private void deletedriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletedriverActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable_Display_Driver.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jTable_Display_Driver.getModel();
        if (selectedRow >= 0) {
            model.removeRow(selectedRow);
        }
         else {
            JOptionPane.showMessageDialog(null, "ERROR");

        }
        try{
             connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/fleetdb", "root", "");
            String sql = "delete  FROM driver where Driver_id=?'"+selectedRow+"'";
            ps = connection.prepareStatement(sql);
         String value=driver_idCombo.getSelectedItem().toString();
         ps.setString(1,value);
             ps.executeUpdate();
            
          
        }
        catch(Exception e){
            e.printStackTrace();
        
        }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   

    }//GEN-LAST:event_deletedriverActionPerformed

    private void jTable_Display_DriverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_Display_DriverMouseClicked
        // TODO add your handling code here:
        //populating textfields with selected row in jtable
        int i = jTable_Display_Driver.getSelectedRow();
        TableModel model = jTable_Display_Driver.getModel();
        firstname.setText(model.getValueAt(i, 1).toString());
        lastname.setText(model.getValueAt(i, 2).toString());
        //gender.setText(model.getValueAt(i, 3).toString());
        phonenumber.setText(model.getValueAt(i, 4).toString());
        String sex=model.getValueAt(i,3).toString();
        if(sex.equals ("Male") ){
           maleradiobtn.setSelected(true);
        }
        else{
            femaleradiobtn.setSelected(true);
        }
        //String id=(model.getValueAt(i,5).toString());
        //switch(id){
           //case1: 
    

    }//GEN-LAST:event_jTable_Display_DriverMouseClicked

    private void femaleradiobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleradiobtnActionPerformed

       gender= "Female";
    }//GEN-LAST:event_femaleradiobtnActionPerformed

    private void maleradiobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleradiobtnActionPerformed
        // TODO add your handling code here:
        gender="Male";
    }//GEN-LAST:event_maleradiobtnActionPerformed

    private void driver_idComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_driver_idComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_driver_idComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Driver_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Driver_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Driver_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Driver_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Driver_Details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adddriver;
    private javax.swing.JButton back;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton deletedriver;
    private javax.swing.JComboBox<String> driver_idCombo;
    private javax.swing.JRadioButton femaleradiobtn;
    private java.awt.TextField firstname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable_Display_Driver;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.TextField lastname;
    private javax.swing.JRadioButton maleradiobtn;
    private java.awt.TextField phonenumber;
    private javax.swing.JButton updatedriver;
    // End of variables declaration//GEN-END:variables
     private String gender;
}
