
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import models.vehicles;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author EVELYN
 */
public class Vehicle_Details extends javax.swing.JFrame {

    Connection connection = null;
    PreparedStatement ps = null;
    ResultSet rs = null;

    public void setVehicle() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/fleetdb", "root", "");
            ArrayList<String> groupNames = new ArrayList<String>();
            String sql = "Select vehicle_id from vehicle";
            PreparedStatement ps = connection.prepareStatement(sql);
            rs = ps.executeQuery();
            while (rs.next()) {
                String name = rs.getString("vehicle_id");
                System.out.println(name);
                groupNames.add(name);

            }
            rs.close();

            //        Populate ComboBox 
            DefaultComboBoxModel model = new DefaultComboBoxModel(groupNames.toArray());
            jComboBox_Driver_id.setModel(model);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * Creates new form Vehicle_Details
     */
    public Vehicle_Details() {
        initComponents();
        //method for jtable population
        show_vehicle();
        //method for combobox population
        setVehicle();
    }

    public ArrayList<vehicles> vehiclelist() {
        ArrayList<vehicles> vehiclelist = new ArrayList<>();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/fleetdb", "root", "");
            String sql = "SELECT * FROM vehicle";
            ps = connection.prepareStatement(sql);
            rs = ps.executeQuery();
            vehicles vehicle;
            while (rs.next()) {
                vehicle = new vehicles(rs.getString("vehicle_id"),
                        rs.getString("model"),
                        rs.getString("type"),
                        rs.getString("color"));
                vehiclelist.add(vehicle);
            }
        } catch (Exception e) {
            e.printStackTrace();
            //JOptionPane.showMessageDialog(null,e);

        }
        return vehiclelist;
    }

    public void show_vehicle() {
        int i;
        ArrayList<vehicles> list = vehiclelist();
        DefaultTableModel model = (DefaultTableModel) jTable_Display_Vehicle.getModel();
        Object[] row = new Object[4];
        for (i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getVehicle_id();
            row[1] = list.get(i).getModel();
            row[2] = list.get(i).getType();
            row[3] = list.get(i).getColor();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Display_Vehicle = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        delete_driver = new javax.swing.JButton();
        add_vehicle = new javax.swing.JButton();
        update_vehicle = new javax.swing.JButton();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        modell = new java.awt.TextField();
        label3 = new java.awt.Label();
        type = new java.awt.TextField();
        label4 = new java.awt.Label();
        colour = new java.awt.TextField();
        back = new javax.swing.JButton();
        jComboBox_Driver_id = new javax.swing.JComboBox<>();
        label5 = new java.awt.Label();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jTable_Display_Vehicle.setBackground(new java.awt.Color(77, 184, 255));
        jTable_Display_Vehicle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "vehicle_id", "model", "type", "color"
            }
        ));
        jTable_Display_Vehicle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_Display_VehicleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Display_Vehicle);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WELCOME TO LYNX FLEET MANAGEMENT SYSTEM");

        delete_driver.setBackground(new java.awt.Color(255, 255, 255));
        delete_driver.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        delete_driver.setForeground(new java.awt.Color(0, 0, 0));
        delete_driver.setText("DELETE VEHICLE");
        delete_driver.setBorder(null);
        delete_driver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_driverActionPerformed(evt);
            }
        });

        add_vehicle.setBackground(new java.awt.Color(255, 255, 255));
        add_vehicle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        add_vehicle.setForeground(new java.awt.Color(0, 0, 0));
        add_vehicle.setText("ADD VEHICLE");
        add_vehicle.setBorder(null);
        add_vehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_vehicleActionPerformed(evt);
            }
        });

        update_vehicle.setBackground(new java.awt.Color(255, 255, 255));
        update_vehicle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        update_vehicle.setForeground(new java.awt.Color(0, 0, 0));
        update_vehicle.setText("UPDATE VEHICLE");
        update_vehicle.setBorder(null);
        update_vehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_vehicleActionPerformed(evt);
            }
        });

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("VEHICLE DETAILS");

        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("MODEL");

        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setText("TYPE");

        label4.setForeground(new java.awt.Color(255, 255, 255));
        label4.setText("COLOUR");

        back.setBackground(new java.awt.Color(255, 255, 255));
        back.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        back.setForeground(new java.awt.Color(0, 0, 0));
        back.setText("BACK");
        back.setBorder(null);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jComboBox_Driver_id.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_Driver_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_Driver_idActionPerformed(evt);
            }
        });

        label5.setForeground(new java.awt.Color(255, 255, 255));
        label5.setText("VEHICLE ID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(117, 117, 117)
                            .addComponent(update_vehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(109, 109, 109)
                            .addComponent(add_vehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(delete_driver, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(label2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label5, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(modell, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(colour, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBox_Driver_id, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 903, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 852, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_Driver_id, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(modell, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(colour, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(update_vehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add_vehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delete_driver, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(356, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(99, 99, 99))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_vehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_vehicleActionPerformed
        // TODO add your handling code here:
        ADD_VEHICLE addvehicle = new ADD_VEHICLE();
        addvehicle.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_add_vehicleActionPerformed

    private void update_vehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_vehicleActionPerformed
        // TODO add your handling code here:
        // UPDATE_VEHICLE updatevehicle=new UPDATE_VEHICLE();
        //updatevehicle.setVisible(true);
        //this.setVisible(false);
        try {
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/fleetdb", "root", "");
            ps = connection.prepareStatement("UPDATE vehicle SET `model`=?, `type`=?,`color`=? WHERE `vehicle_id`=?");
            // ps = connection.prepareStatement("UPDATE driver SET `First_name`=?, `Last_name`=? ,`Gender`=? ,`Phone_number`=? WHERE `Driver_id`=?");
            ps.setString(1, modell.getText());
            ps.setString(2, type.getText());
            //ps.setString(3, gender);
            ps.setString(3, colour.getText());
            String value = jComboBox_Driver_id.getSelectedItem().toString();
            ps.setString(4, value);
            int rowaffected = ps.executeUpdate();
            if (rowaffected > 0) {
                System.out.println("updated");
                JOptionPane.showMessageDialog(null, "VEHICLE UPDATED SUCCESSFULLY");
            }
            System.out.println("updated");
            JOptionPane.showMessageDialog(null, "VEHICLE UPDATED SUCCESSFULLY");
        } catch (Exception e) {
            e.printStackTrace();

        }

    }//GEN-LAST:event_update_vehicleActionPerformed

    private void delete_driverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_driverActionPerformed
        // TODO add your handling code here:
        //The selected Row is deleted
        int selectedRow = jTable_Display_Vehicle.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jTable_Display_Vehicle.getModel();
        if (selectedRow >= 0) {
            model.removeRow(selectedRow);
        } else {
            JOptionPane.showMessageDialog(null, "ERROR");

        }
        try {
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/fleetdb", "root", "");
            String sql = "DELETE  FROM vehicle where vehicle_id=?'" + selectedRow + "'";
            ps = connection.prepareStatement(sql);
            String value = jComboBox_Driver_id.getSelectedItem().toString();
            ps.setString(1, value);
            ps.executeUpdate();
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_delete_driverActionPerformed

    private void jTable_Display_VehicleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_Display_VehicleMouseClicked
        // TODO add your handling code here:
        int i = jTable_Display_Vehicle.getSelectedRow();
        TableModel model = jTable_Display_Vehicle.getModel();
        modell.setText(model.getValueAt(i, 1).toString());
        type.setText(model.getValueAt(i, 2).toString());
        colour.setText(model.getValueAt(i, 3).toString());


    }//GEN-LAST:event_jTable_Display_VehicleMouseClicked

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        Admin_dashboard admin = new Admin_dashboard();
        admin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void jComboBox_Driver_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_Driver_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_Driver_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vehicle_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vehicle_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vehicle_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vehicle_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vehicle_Details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_vehicle;
    private javax.swing.JButton back;
    private java.awt.TextField colour;
    private javax.swing.JButton delete_driver;
    private javax.swing.JComboBox<String> jComboBox_Driver_id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Display_Vehicle;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.TextField modell;
    private java.awt.TextField type;
    private javax.swing.JButton update_vehicle;
    // End of variables declaration//GEN-END:variables
}
